using System;
using System.Collections.Generic;
using System.Text;

namespace MCronberg
{
    using System;
    using System.Linq;
    using System.Reflection;

    public static class MyExtensions
    {
        public static void Dump(this object o, bool indented = true)
        {
            Console.WriteLine(GetJson(o, indented));
        }

        public static void Dump<T>(this IEnumerable<T> lst, bool indented = true)
        {
            foreach (var i in lst)
            {
                Console.WriteLine(GetJson(i, indented));
            }
        }

        public static string ToJsonString(this object obj, bool indented = false)
        {
            try
            {
                return GetJson(obj, indented);
            }
            catch (System.Exception ex)
            {
                return ex.Message;
            }
        }

        public static void ToStringEx(this Type type, string filePath, bool showBackingFields = false, bool showGetSetAddMethods = false, bool showObjectMembers = false, bool showFullName = false, int typeStringLength = 25, bool showAccessStaticInstance = true)
        {
            string txt = ToStringEx(type, showBackingFields, showGetSetAddMethods, showObjectMembers, showFullName, typeStringLength, showAccessStaticInstance);
            System.IO.File.WriteAllText(filePath, txt);
        }

        public static string ToStringEx(this Type type, bool showBackingFields = false, bool showGetSetAddMethods = false, bool showObjectMembers = false, bool showFullName = false, int typeStringLength = 25, bool showAccessStaticInstance = true)
        {
            string non = "none";
            string pre = "  ";
            string pri = "private  ";
            string pub = "public   ";
            string sta = "static   ";
            string ins = "instance ";
            int lengthType = typeStringLength;

            if (!showAccessStaticInstance)
                lengthType = 0;

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine(showFullName ? type.FullName : type.Name);
            sb.AppendLine(new string('-', (showFullName ? type.FullName : type.Name).Length));

            var fields = type.GetFields(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static).OrderBy(i => i.IsStatic).ThenBy(i => i.IsPublic).ThenBy(i => i.Name).ToList();
            if (!showBackingFields)
                fields = fields.Where(i => !i.Name.Contains("<")).ToList();
            sb.AppendLine();
            if (!showBackingFields)
                sb.AppendLine("Fields (without any autogenerated backing fields): ");
            else
                sb.AppendLine("Fields: ");
            sb.AppendLine();
            if (fields.Count == 0)
                sb.AppendLine(pre + non);
            else
            {
                foreach (var i in fields)
                {
                    var p = (i.IsPublic ? pub : "") + (!i.IsPublic ? pri : "") + (i.IsStatic ? sta : "") + (!i.IsStatic ? ins : "");
                    if (!showAccessStaticInstance)
                        p = "";
                    string t = "";
                    if (i.FieldType.IsGenericType)
                        t = getTypeAsString(i.FieldType);
                    else
                        t = showFullName ? i.FieldType.FullName : i.FieldType.Name;

                    sb.AppendLine(pre + p + " " + truncate(t, lengthType) + " " + i.Name);
                }
            }

            sb.AppendLine();
            sb.AppendLine("Properties:");
            sb.AppendLine();
            var properties = type.GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static).OrderBy(i => i.Name).ToList();
            if (properties.Count == 0)
                sb.AppendLine(pre + non);
            else
            {
                foreach (var i in type.GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).OrderBy(i => i.Name).ToList())
                {
                    sb.AppendLine(propertyString(i));
                }

                foreach (var i in type.GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public).OrderBy(i => i.Name).ToList())
                {
                    sb.AppendLine(propertyString(i));
                }
            }

            sb.AppendLine();
            sb.AppendLine("Constructors:");
            sb.AppendLine();
            var constructors = type.GetConstructors(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static).OrderBy(i => i.IsStatic).ThenBy(i => i.IsPublic).ThenBy(i => i.Name).ToList();
            if (constructors.Count == 0)
                sb.AppendLine(pre + non);
            else
            {
                foreach (var i in constructors)
                {
                    List<string> pa = new List<string>();
                    foreach (ParameterInfo para in i.GetParameters())
                        pa.Add(getTypeAsString(para.ParameterType, showFullName) + " " + para.Name);
                    var p = (i.IsPublic ? pub : "") + (!i.IsPublic ? pri : "") + (i.IsStatic ? sta : "") + (!i.IsStatic ? ins : "");
                    if (!showAccessStaticInstance)
                        p = "";
                    sb.AppendLine(pre + p + " " + truncate("", lengthType) + " " + type.Name + "(" + string.Join(',', pa).Replace(",", ", ") + ")");
                }
            }

            sb.AppendLine();
            if (!showGetSetAddMethods)
                sb.AppendLine("Methods (without any autogenerated backing methods):");
            else
                sb.AppendLine("Methods:");
            sb.AppendLine();
            var methods = type.GetMethods(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static).OrderBy(i => i.IsStatic).ThenBy(i => i.IsPublic).ThenBy(i => i.Name).ToList();
            if (!showGetSetAddMethods)
                methods = methods.Where(i => !i.Name.StartsWith("get_") && !i.Name.StartsWith("set_") && !i.Name.StartsWith("add_")).ToList();

            methods = methods.Where(i => !i.Name.StartsWith("<")).ToList();

            string[] objectM = { "Finalize", "ToString", "MemberwiseClone", "Equals", "GetHashCode", "GetType" };
            if (!showObjectMembers)
                methods = methods.Where(i => !objectM.Contains(i.Name)).ToList();

            if (methods.Count == 0)
                sb.AppendLine(pre + non);
            else
            {
                foreach (var i in methods)
                {
                    List<string> pa = new List<string>();
                    foreach (ParameterInfo para in i.GetParameters())
                        pa.Add(getTypeAsString(para.ParameterType, showFullName) + " " + para.Name);
                    var p = (i.IsPublic ? pub : "") + (!i.IsPublic ? pri : "") + (i.IsStatic ? sta : "") + (!i.IsStatic ? ins : "");
                    if (!showAccessStaticInstance)
                        p = "";
                    sb.AppendLine(pre + p + " " + truncate(getTypeAsString(i.ReturnType, showFullName), lengthType) + " " + i.Name + "(" + string.Join(',', pa).Replace(",", ", ") + ")");
                }
            }

            sb.AppendLine();
            sb.AppendLine("Events:");
            sb.AppendLine();
            var events = type.GetEvents(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static).OrderBy(i => i.Name).ToList();
            if (events.Count == 0)
                sb.AppendLine(pre + non);
            else
            {
                foreach (var i in events)
                {
                    sb.AppendLine(pre + pub + ins + " " + truncate(getTypeAsString(i.EventHandlerType, showFullName), lengthType) + i.Name);
                }
            }

            return sb.ToString();

            string propertyString(PropertyInfo i)
            {
                var p = pub + ins;
                if (!showAccessStaticInstance)
                    p = "";
                string g = "", s = "", gs = "";
                if (i.CanRead)
                    g = (i.GetMethod.IsPublic ? pub.Trim() : pri.Trim()) + " " + (i.CanRead ? "get" : "");

                if (i.CanWrite)
                {
                    g += ", ";
                    s = (i.SetMethod.IsPublic ? pub.Trim() : pri.Trim()) + " " + (i.CanWrite ? "set" : "");
                }
                if (s + g != "")
                    gs = "(" + g + (s != "" ? " " : "") + s + ")";
                return pre + p + " " + truncate(getTypeAsString(i.PropertyType, showFullName), lengthType) + " " + i.Name + " " + gs;
            }

            string truncate(string txt, int lenght)
            {
                if (lenght == 0)
                    return txt;
                if (txt.Length <= lenght)
                    return txt.PadRight(lenght);
                else
                    return txt.Substring(0, lenght - 3) + "...";
            }

            string getTypeAsString(Type t, bool useFullName = false)
            {
                if (!t.IsGenericType)
                    return useFullName ? t.FullName : t.Name;
                string genericTypeName = t.GetGenericTypeDefinition().Name;
                genericTypeName = genericTypeName.Substring(0,
                    genericTypeName.IndexOf('`'));
                string genericArgs = string.Join(", ",
                    t.GetGenericArguments()
                        .Select(ta => getTypeAsString(ta)).ToArray());
                return genericTypeName + "<" + genericArgs + ">";
            }
        }

        public static string ToStringEx(this object obj, bool showFields = true, bool showProperties = true, bool showMethods = true)
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            string types = "(";
            if (showFields)
                types += "fields ";
            if (showProperties)
                types += "properties ";
            if (showMethods)
                types += "methods ";

            types = types.Trim().Replace(" ", ",") + ")";
            if (types.Split(',').Length == 1)
                types = types.Replace(")", " only)");

            if (types.Split(',').Length == 2)
                types = types.Replace(",", " and ");
            else
                types = types.Replace(",", ", ");

            string header = "Showing members " + types + " from object of type " + obj.GetType().ToString() + ":";
            sb.AppendLine(header);
            sb.Append(new string('-', header.Length));
            sb.AppendLine("");
            if (showFields)
            {
                sb.AppendLine("Fields:");
                sb.AppendLine("");
                foreach (var item in obj.GetType().GetFields(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.DeclaredOnly).OrderBy(i => i.Name))
                {
                    string a = "Private ";
                    if (item.IsPublic)
                        a = "Public ";
                    object value = item.GetValue(obj);

                    if (value == null)
                        value = "null";
                    sb.AppendLine(print(a, 10) + " " + print(item.FieldType.ToString(), 25) + " " + print(item.Name, 30) + " " + print(value.ToString(), 20));
                }
                sb.AppendLine("");
            }
            if (showProperties)
            {
                sb.AppendLine("Properties:");
                sb.AppendLine("");
                foreach (var item in obj.GetType().GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.DeclaredOnly).OrderBy(i => i.Name))
                {
                    string a = "";
                    if (item.CanRead && item.CanWrite)
                        a = "get/set";
                    if (item.CanRead && !item.CanWrite)
                        a = "get";
                    if (!item.CanRead && item.CanWrite)
                        a = "set";
                    object value = null;
                    try
                    {
                        value = item.GetValue(obj);
                    }
                    catch (System.Exception)
                    {
                    }

                    if (value == null)
                        value = "null";
                    sb.AppendLine("" + print(a, 10) + " " + print(item.PropertyType.ToString(), 25) + " " + print(item.Name, 30) + " " + print(value.ToString(), 20) + "");
                }
                sb.AppendLine("");
            }
            if (showMethods)
            {
                sb.AppendLine("Methods:");
                sb.AppendLine("");
                foreach (var item in obj.GetType().GetMethods(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.DeclaredOnly).OrderBy(i => i.Name))
                {
                    string a = "Private ";
                    if (item.IsPublic)
                        a = "Public ";
                    object value = "";
                    if (value == null)
                        value = "null";
                    sb.AppendLine("" + print(a, 10) + " " + print(item.ReturnType.ToString(), 25) + " " + print(item.Name, 30) + " " + print(value.ToString(), 20));
                }
                sb.AppendLine("");

                sb.AppendLine("More info:");
                sb.AppendLine("");
                sb.AppendLine(print("Primitive", 37) + print(obj.GetType().IsPrimitive.ToString(), 30));
                sb.AppendLine(print("ValueType", 37) + print(obj.GetType().IsValueType.ToString(), 30));
                sb.AppendLine(print("ReferenceType", 37) + print(obj.GetType().IsClass.ToString(), 30));
                sb.AppendLine(print("Array", 37) + print(obj.GetType().IsArray.ToString(), 30));
                sb.AppendLine(print("Abstract", 37) + print(obj.GetType().IsAbstract.ToString(), 30));
                sb.AppendLine(print("Enum", 37) + print(obj.GetType().IsEnum.ToString(), 30));
                if (obj.GetType().IsEnum)
                    sb.AppendLine(print("Enum value", 37) + print(obj.ToString(), 30));
                sb.AppendLine(print("Interface", 37) + print(obj.GetType().IsInterface.ToString(), 30));
                sb.AppendLine(print("Sealed", 37) + print(obj.GetType().IsSealed.ToString(), 30));
            }
            string print(string txt, int length)
            {
                if (txt.Length > length)
                {
                    txt = txt.Substring(0, length - 2) + "..";
                }
                return txt.PadRight(length);
            }

            return sb.ToString();
        }

        private static string GetJson(object o, bool indented)
        {
            return System.Text.Json.JsonSerializer.Serialize(o, new System.Text.Json.JsonSerializerOptions { WriteIndented = indented });
        }
    }
}